# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0011_programslot_remove_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rrule',
            options={'ordering': ('pk',), 'verbose_name': 'Recurrence rule', 'verbose_name_plural': 'Recurrence rules'},
        ),
        migrations.AlterField(
            model_name='broadcastformat',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='broadcastformat',
            name='text_color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Text color'),
        ),
        migrations.AlterField(
            model_name='musicfocus',
            name='big_button',
            field=models.ImageField(blank=True, null=True, upload_to='buttons', verbose_name='Big button image'),
        ),
        migrations.AlterField(
            model_name='musicfocus',
            name='button',
            field=models.ImageField(blank=True, null=True, upload_to='buttons', verbose_name='Button image'),
        ),
        migrations.AlterField(
            model_name='musicfocus',
            name='button_hover',
            field=models.ImageField(blank=True, null=True, upload_to='buttons', verbose_name='Button image (hover)'),
        ),
        migrations.AlterField(
            model_name='programslot',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='programslot',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='rrule',
            name='freq',
            field=models.IntegerField(choices=[(1, 'Monthly'), (2, 'Weekly'), (3, 'Daily')], default=1, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='show',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='show_images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='showinformation',
            name='big_button',
            field=models.ImageField(blank=True, null=True, upload_to='buttons', verbose_name='Big button image'),
        ),
        migrations.AlterField(
            model_name='showinformation',
            name='button',
            field=models.ImageField(blank=True, null=True, upload_to='buttons', verbose_name='Button image'),
        ),
        migrations.AlterField(
            model_name='showinformation',
            name='button_hover',
            field=models.ImageField(blank=True, null=True, upload_to='buttons', verbose_name='Button image (hover)'),
        ),
        migrations.AlterField(
            model_name='showtopic',
            name='big_button',
            field=models.ImageField(blank=True, null=True, upload_to='buttons', verbose_name='Big button image'),
        ),
        migrations.AlterField(
            model_name='showtopic',
            name='button',
            field=models.ImageField(blank=True, null=True, upload_to='buttons', verbose_name='Button image'),
        ),
        migrations.AlterField(
            model_name='showtopic',
            name='button_hover',
            field=models.ImageField(blank=True, null=True, upload_to='buttons', verbose_name='Button image (hover)'),
        ),
    ]
