# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0012_auto_20171129_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.TextField(blank=True, max_length=7, verbose_name='Color'),
        ),
    ]
