# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 01:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0012_auto_20171012_0056'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programslot',
            unique_together=set([]),
        ),
    ]
