# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0012_auto_20171109_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ('language',),
            },
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ('dstart', 'tstart'), 'verbose_name': 'Schedule', 'verbose_name_plural': 'Schedules'},
        ),
        migrations.AddField(
            model_name='show',
            name='language',
            field=models.ManyToManyField(blank=True, related_name='language', to='program.Language', verbose_name='Language'),
        ),
    ]
