# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0013_auto_20171012_0108'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programslot',
            unique_together=set([('rrule', 'byweekday', 'dstart', 'tstart')]),
        ),
    ]
