# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0014_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='audio_url',
            field=models.TextField(blank=True, editable=False, verbose_name='Direct URL to a linked audio file'),
        ),
    ]
