# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0015_auto_20171013_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='start',
            field=models.DateTimeField(verbose_name='Start time'),
        ),
    ]
