# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-02 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0016_auto_20171213_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='fallback_playlist_id',
        ),
        migrations.RemoveField(
            model_name='show',
            name='fallback_pool',
        ),
        migrations.AddField(
            model_name='schedule',
            name='fallback_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fallback ID'),
        ),
        migrations.AddField(
            model_name='show',
            name='fallback_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fallback ID'),
        ),
        migrations.AlterField(
            model_name='host',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='height', help_text="Upload a picture of yourself. Images are automatically cropped around the 'Primary Point of Interest'. Click in the image to change it and press Save.", null=True, upload_to='host_images', verbose_name='Profile picture', width_field='width'),
        ),
    ]
