# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 18:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Biography')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('googleplus_url', models.URLField(blank=True, verbose_name='Google+ URL')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='Youtube URL')),
                ('dorftv_url', models.URLField(blank=True, verbose_name='DorfTV URL')),
                ('cba_url', models.URLField(blank=True, verbose_name='CBA URL')),
                ('cba_username', models.CharField(blank=True, max_length=60, verbose_name='CBA Username')),
                ('cba_user_token', models.CharField(blank=True, max_length=255, verbose_name='CBA Token')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI')),
                ('height', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Image Height')),
                ('width', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Image Width')),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, height_field='height', null=True, upload_to='user_images', verbose_name='Profile picture', width_field='width')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
